# Generated by Django 4.0.7 on 2022-09-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_album_owner_photo_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('upload_dt',)},
        ),
    ]
