# Generated by Django 4.0.7 on 2022-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_alter_photo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre_description',
            field=models.CharField(blank=True, max_length=1000000, verbose_name='Genre Description'),
        ),
    ]
