# Generated by Django 4.0.7 on 2022-09-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_album_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='genre_description',
            field=models.TextField(blank=True, verbose_name='Genre Description'),
        ),
    ]
