# Generated by Django 4.0.7 on 2022-09-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_alter_album_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='year'),
        ),
    ]
